"""Tests for docs/video_script.md — written BEFORE the document (TDD).

Acceptance criteria (GitHub Issue #52):
  (a) File docs/video_script.md exists with all 10 required sections.
  (b) Each section uses H2 headers, blockquotes for narration, relative figure paths.
  (c) A summary table at the top maps section → figure → key statistic.
  (d) Each section includes a timing estimate.
  (e) Total word count is between 2000 and 4000.
  (f) All referenced figure filenames match those generated by the narrative script.
  (g) Key statistics are cited (Jail, Illinois, orange/arancione, 3 case).
  (h) Tone is educational and accessible (written in Italian).
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_DOCS_DIR = Path(__file__).parent.parent / "docs"
_SCRIPT_PATH = _DOCS_DIR / "video_script.md"

# Figure filenames generated by come_vincere_al_monopoli.py
_EXPECTED_FIGURES = {
    "heatmap.png",
    "roi_bars.png",
    "win_rate_curves.png",
    "net_worth.png",
    "game_animation.mp4",
}

# Required H2 section titles (partial matches in Italian)
_EXPECTED_SECTION_COUNT = 10

# Key statistics that must appear somewhere in the document
_KEY_STATS = [
    "5.89",  # Jail landing probability
    "3.18",  # Illinois Ave probability
    "16.7",  # 7 is the most frequent dice sum
]

# Key Italian terms indicating educational tone
_ITALIAN_KEYWORDS = [
    "probabilità",
    "casella",
    "proprietà",
    "strategia",
    "Prigione",
]


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def script_content() -> str:
    """Return the full text of docs/video_script.md."""
    return _SCRIPT_PATH.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def h2_sections(script_content: str) -> list[str]:
    """Return all H2 section titles found in the document."""
    return re.findall(r"^## .+", script_content, re.MULTILINE)


# ---------------------------------------------------------------------------
# (a) File existence
# ---------------------------------------------------------------------------


class TestFileExists:
    """The document must exist at the expected path."""

    def test_docs_directory_exists(self) -> None:
        """docs/ directory must exist."""
        assert _DOCS_DIR.exists(), f"docs/ directory not found at {_DOCS_DIR}"
        assert _DOCS_DIR.is_dir()

    def test_video_script_file_exists(self) -> None:
        """docs/video_script.md must exist."""
        assert _SCRIPT_PATH.exists(), f"File not found: {_SCRIPT_PATH}"
        assert _SCRIPT_PATH.is_file()

    def test_file_is_not_empty(self, script_content: str) -> None:
        """docs/video_script.md must not be empty."""
        assert len(script_content.strip()) > 0


# ---------------------------------------------------------------------------
# (a) Section count and structure
# ---------------------------------------------------------------------------


class TestSectionStructure:
    """The document must have exactly 10 H2 sections."""

    def test_has_ten_h2_sections(self, h2_sections: list[str]) -> None:
        """Document must contain exactly 10 H2 section headers."""
        assert len(h2_sections) == _EXPECTED_SECTION_COUNT, (
            f"Expected {_EXPECTED_SECTION_COUNT} H2 sections, "
            f"found {len(h2_sections)}: {h2_sections}"
        )

    def test_sections_are_numbered(self, h2_sections: list[str]) -> None:
        """Each H2 section must include a section number."""
        for section in h2_sections:
            has_number = bool(re.search(r"\d+", section))
            assert has_number, f"Section has no number: {section!r}"

    def test_has_h1_title(self, script_content: str) -> None:
        """Document must have an H1 title."""
        h1_titles = re.findall(r"^# .+", script_content, re.MULTILINE)
        assert len(h1_titles) >= 1, "Document must have at least one H1 title"


# ---------------------------------------------------------------------------
# (b) Narration blockquotes
# ---------------------------------------------------------------------------


class TestNarrationBlockquotes:
    """Each section must contain at least one blockquote for narration text."""

    def test_document_contains_blockquotes(self, script_content: str) -> None:
        """Document must contain blockquote syntax (lines starting with >)."""
        blockquote_lines = [
            line for line in script_content.splitlines() if line.startswith(">")
        ]
        assert len(blockquote_lines) >= 10, (
            f"Expected at least 10 blockquote lines, found {len(blockquote_lines)}"
        )

    def test_blockquotes_appear_in_most_sections(self, script_content: str) -> None:
        """At least 8 of the 10 sections must contain blockquote narration."""
        # Split by H2 and count sections with blockquotes
        sections = re.split(r"^## ", script_content, flags=re.MULTILINE)
        sections_with_blockquotes = sum(1 for s in sections if ">" in s)
        assert sections_with_blockquotes >= 8, (
            f"Expected ≥8 sections with blockquotes, found {sections_with_blockquotes}"
        )


# ---------------------------------------------------------------------------
# (b) Relative figure paths
# ---------------------------------------------------------------------------


class TestFigurePaths:
    """All referenced figures must use relative paths and match script outputs."""

    def test_figures_use_relative_paths(self, script_content: str) -> None:
        """Figure references must use '../figures/' relative path prefix."""
        figure_refs = re.findall(r"\.\./figures/[\w.]+", script_content)
        assert len(figure_refs) >= len(_EXPECTED_FIGURES) - 1, (
            f"Expected at least {len(_EXPECTED_FIGURES) - 1} figure references "
            f"with '../figures/' prefix, found {len(figure_refs)}"
        )

    @pytest.mark.parametrize("figure_name", sorted(_EXPECTED_FIGURES))
    def test_each_expected_figure_is_referenced(
        self, script_content: str, figure_name: str
    ) -> None:
        """Each figure generated by the narrative script must be referenced."""
        assert figure_name in script_content, (
            f"Figure '{figure_name}' not referenced in the video script"
        )


# ---------------------------------------------------------------------------
# (c) Summary table
# ---------------------------------------------------------------------------


class TestSummaryTable:
    """A summary table must appear near the top of the document."""

    def test_document_contains_table(self, script_content: str) -> None:
        """Document must contain a Markdown table (lines with | separators)."""
        table_lines = [
            line
            for line in script_content.splitlines()
            if line.strip().startswith("|") and "|" in line[1:]
        ]
        assert len(table_lines) >= 5, (
            f"Expected ≥5 table rows, found {len(table_lines)}"
        )

    def test_table_references_figures(self, script_content: str) -> None:
        """Summary table must reference figure filenames."""
        # Find the table section (near the top, before first H2)
        pre_sections = script_content.split("##")[0]
        has_figure_ref = any(fig in pre_sections for fig in _EXPECTED_FIGURES)
        assert has_figure_ref, (
            "Summary table at the top must reference figure filenames"
        )


# ---------------------------------------------------------------------------
# (d) Timing estimates
# ---------------------------------------------------------------------------


class TestTimingEstimates:
    """Each section must include a timing estimate."""

    def test_document_contains_timing_estimates(self, script_content: str) -> None:
        """Document must contain timing estimates in seconds or minutes."""
        timing_pattern = re.compile(r"~?\d+\s*(second[io]|minut[io])", re.IGNORECASE)
        timings = timing_pattern.findall(script_content)
        assert len(timings) >= 8, (
            f"Expected ≥8 timing estimates, found {len(timings)}: {timings}"
        )

    def test_timing_estimates_are_reasonable(self, script_content: str) -> None:
        """Timing values must be plausible (between 30s and 300s per section)."""
        second_values = [
            int(m)
            for m in re.findall(r"~?(\d+)\s*second[io]", script_content, re.IGNORECASE)
        ]
        for val in second_values:
            assert 30 <= val <= 300, (
                f"Timing estimate {val}s is outside plausible range (30–300s)"
            )


# ---------------------------------------------------------------------------
# (e) Word count
# ---------------------------------------------------------------------------


class TestWordCount:
    """Total word count must be between 2000 and 4000."""

    def test_minimum_word_count(self, script_content: str) -> None:
        """Document must contain at least 2000 words."""
        words = script_content.split()
        assert len(words) >= 2000, f"Word count too low: {len(words)} (minimum 2000)"

    def test_maximum_word_count(self, script_content: str) -> None:
        """Document must not exceed 4000 words."""
        words = script_content.split()
        assert len(words) <= 4000, f"Word count too high: {len(words)} (maximum 4000)"


# ---------------------------------------------------------------------------
# (f) / (g) Key statistics
# ---------------------------------------------------------------------------


class TestKeyStatistics:
    """Key Monopoly statistics must be cited in the document."""

    @pytest.mark.parametrize("stat", _KEY_STATS)
    def test_key_statistic_is_cited(self, script_content: str, stat: str) -> None:
        """Each key statistic must appear in the document."""
        assert stat in script_content, (
            f"Key statistic '{stat}' not found in the video script"
        )

    def test_orange_group_is_highlighted(self, script_content: str) -> None:
        """Orange/arancione color group must be mentioned as high-ROI."""
        has_orange = (
            "arancione" in script_content.lower() or "orange" in script_content.lower()
        )
        assert has_orange, "Orange color group must be mentioned as high ROI"

    def test_three_houses_strategy_mentioned(self, script_content: str) -> None:
        """The 3-houses rule must be explicitly mentioned."""
        has_three_houses = (
            "3 case" in script_content or "tre case" in script_content.lower()
        )
        assert has_three_houses, "The 3-houses strategy must be mentioned"

    def test_jail_mentioned(self, script_content: str) -> None:
        """Jail/Prigione must be mentioned with its probability."""
        has_jail = "Prigione" in script_content or "prigione" in script_content
        assert has_jail, "Jail (Prigione) must be mentioned in the document"


# ---------------------------------------------------------------------------
# (h) Italian language and educational tone
# ---------------------------------------------------------------------------


class TestItalianTone:
    """Document must be written in Italian with educational tone."""

    @pytest.mark.parametrize("keyword", _ITALIAN_KEYWORDS)
    def test_italian_keyword_present(self, script_content: str, keyword: str) -> None:
        """Key Italian words must appear in the document."""
        assert keyword in script_content, (
            f"Italian keyword '{keyword}' not found — document may not be in Italian"
        )

    def test_no_english_section_headers(self, h2_sections: list[str]) -> None:
        """Section headers must be in Italian (no English-only section titles)."""
        english_only_words = {"introduction", "conclusion", "section", "chapter"}
        for section in h2_sections:
            section_lower = section.lower()
            is_english_only = all(word in section_lower for word in english_only_words)
            assert not is_english_only, (
                f"Section header appears to be in English: {section!r}"
            )
